-- Insert games data
INSERT INTO games (slug, name, image) VALUES
('wingspan', 'Wingspan', '🦅'),
('gloomhaven', 'Gloomhaven', '⚔️'),
('azul', 'Azul', '🎨'),
('terraforming-mars', 'Terraforming Mars', '🚀'),
('spirit-island', 'Spirit Island', '🏝️'),
('dominion', 'Dominion', '👑'),
('7-wonders', '7 Wonders', '🏛️'),
('pandemic', 'Pandemic', '🦠'),
('arkham-horror-lcg', 'Arkham Horror: The Card Game', '🐙'),
('netrunner', 'Android: Netrunner', '💻'),
('race-for-the-galaxy', 'Race for the Galaxy', '🌌'),
('splendor', 'Splendor', '💎'),
('ticket-to-ride', 'Ticket to Ride', '🚂'),
('love-letter', 'Love Letter', '💌'),
('machi-koro', 'Machi Koro', '🏘️'),
('king-of-tokyo', 'King of Tokyo', '🦖'),
('citadels', 'Citadels', '🏰'),
('coup', 'Coup', '🎭'),
('sushi-go', 'Sushi Go!', '🍣'),
('bang', 'BANG!', '🤠'),
('uno', 'UNO', '🔴'),
('exploding-kittens', 'Exploding Kittens', '💥'),
('cards-against-humanity', 'Cards Against Humanity', '🃏'),
('magic-the-gathering', 'Magic: The Gathering', '🔮'),
('pokemon-tcg', 'Pokémon Trading Card Game', '⚡'),
('yu-gi-oh', 'Yu-Gi-Oh!', '🎴'),
('legendary', 'Legendary: A Marvel Deck Building Game', '🦸'),
('ascension', 'Ascension', '⚔️'),
('star-realms', 'Star Realms', '🚀'),
('munchkin', 'Munchkin', '🗡️'),
('fluxx', 'Fluxx', '🌀'),
('smash-up', 'Smash Up', '💥'),
('red-dragon-inn', 'The Red Dragon Inn', '🍺'),
('betrayal-at-house-on-the-hill', 'Betrayal at House on the Hill', '🏚️'),
('elder-sign', 'Elder Sign', '👁️'),
('mansions-of-madness', 'Mansions of Madness', '🕯️'),
('eldritch-horror', 'Eldritch Horror', '🌍'),
('arkham-horror', 'Arkham Horror', '🏚️'),
('twilight-imperium', 'Twilight Imperium', '🌌'),
('agricola', 'Agricola', '🚜'),
('puerto-rico', 'Puerto Rico', '🏝️'),
('power-grid', 'Power Grid', '⚡'),
('through-the-ages', 'Through the Ages', '🏛️'),
('brass-birmingham', 'Brass: Birmingham', '🏭'),
('food-chain-magnate', 'Food Chain Magnate', '🍔'),
('great-western-trail', 'Great Western Trail', '🤠'),
('scythe', 'Scythe', '🤖'),
('everdell', 'Everdell', '🌳'),
('root', 'Root', '🦝'),
('clank', 'Clank!', '🗡️'),
('concordia', 'Concordia', '🏛️'),
('istanbul', 'Istanbul', '🕌'),
('lords-of-waterdeep', 'Lords of Waterdeep', '🏰'),
('viticulture', 'Viticulture', '🍇'),
('caverna', 'Caverna', '⛏️'),
('le-havre', 'Le Havre', '🚢'),
('ora-et-labora', 'Ora et Labora', '⛪'),
('fields-of-arle', 'Fields of Arle', '🌾'),
('a-feast-for-odin', 'A Feast for Odin', '🛡️'),
('gaia-project', 'Gaia Project', '🌌'),
('terra-mystica', 'Terra Mystica', '🏔️'),
('robinson-crusoe', 'Robinson Crusoe', '🏝️'),
('dead-of-winter', 'Dead of Winter', '🧟'),
('mice-and-mystics', 'Mice and Mystics', '🐭'),
('zombicide', 'Zombicide', '🧟‍♂️'),
('blood-rage', 'Blood Rage', '⚔️'),
('rising-sun', 'Rising Sun', '🌅'),
('massive-darkness', 'Massive Darkness', '🗡️'),
('sheriff-of-nottingham', 'Sheriff of Nottingham', '🏹'),
('castle-panic', 'Castle Panic', '🏰'),
('forbidden-island', 'Forbidden Island', '🏝️'),
('forbidden-desert', 'Forbidden Desert', '🏜️'),
('forbidden-sky', 'Forbidden Sky', '⚡'),
('flash-point', 'Flash Point: Fire Rescue', '🚒'),
('hanabi', 'Hanabi', '🎆'),
('the-mind', 'The Mind', '🧠'),
('just-one', 'Just One', '✏️'),
('wavelength', 'Wavelength', '📡'),
('codenames', 'Codenames', '🕵️'),
('codenames-duet', 'Codenames: Duet', '👫'),
('codenames-pictures', 'Codenames: Pictures', '🖼️'),
('dixit', 'Dixit', '🎨'),
('mysterium', 'Mysterium', '👻'),
('one-night-ultimate-werewolf', 'One Night Ultimate Werewolf', '🐺'),
('the-resistance-avalon', 'The Resistance: Avalon', '⚔️'),
('secret-hitler', 'Secret Hitler', '🎭'),
('spyfall', 'Spyfall', '🕵️‍♂️'),
('telestrations', 'Telestrations', '✏️'),
('wits-and-wagers', 'Wits & Wagers', '🎲'),
('camel-up', 'Camel Up', '🐪'),
('kingdomino', 'Kingdomino', '👑'),
('azul-summer-pavilion', 'Azul: Summer Pavilion', '🏛️'),
('azul-stained-glass', 'Azul: Stained Glass of Sintra', '🪟'),
('sagrada', 'Sagrada', '🪟'),
('century-spice-road', 'Century: Spice Road', '🌶️'),
('century-eastern-wonders', 'Century: Eastern Wonders', '🏝️'),
('century-new-world', 'Century: A New World', '🌎'),
('patchwork', 'Patchwork', '🧵'),
('jaipur', 'Jaipur', '💎'),
('lost-cities', 'Lost Cities', '🗺️'),
('hive', 'Hive', '🐝'),
('targi', 'Targi', '🏜️'),
('hanamikoji', 'Hanamikoji', '🌸');
